# Generated by Django 2.2.12 on 2020-10-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaapi', '0003_auto_20201022_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_municipio',
            field=models.ForeignKey(blank=True, db_column='id_municipio', on_delete=django.db.models.deletion.CASCADE, to='pruebaapi.Municipio'),
        ),
    ]
