# Generated by Django 2.2.12 on 2020-10-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaapi', '0006_auto_20201022_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_municipio',
            field=models.IntegerField(blank=True),
        ),
    ]
